/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:656561ca-d788-4fd0-a9e4-d5a8991e2a35",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_zPAij3vw9",
    "aws_user_pools_web_client_id": "10hcb79a0c73oi8ehtit0ilo5n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jkike6fy6zcgflybxsanqpxq74.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ixjz6fqm5fe37ctpoxx3mrmd2y"
};


export default awsmobile;
